testname: Rhythmic Complexity Perceptive Test
testId: Rhythmic_Complexity_Test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: generic
      id: first_page
      name: "Welcome and thank you for partecipating!"
      content: >
              Welcome to this perceptive test, which is part of a research for a Music Engineering MSc thesis at Politecnico di Milano. <br />
              The test is intended to investigate the idea of rhythmic complexity, as it is one of the most interesting and determinant properties when it comes to describe a rhythm, which is itself one of the main aspects involved in music. 
              Of course, listening to music is a subjective experience, so it is very hard to find formal definitions of the aspects involved in this phenomena. That's why perceptive tests are so important. 
              Moreover, being the perceived rhythmic complexity one of the most challenging-to-define features for a music track, a definition of it would constitute a big step forward in a Music Information Retrieval context. 
              Also, with such a definition, many unexplored applications would become accessible, both in the analytical and generative sense. <br />
              <br /> 

              So, first of all, thank you for your collaboration. Your contribute is very important. <br />
              

              Following, the structure of the test is described. <br />
              <br /> 
              
              You are going to listen to some rhythmic patterns, and for each of them you will be asked to express a rating to tell how complex you find them from a rhythmic point of view. <br />
              Make sure not to listen to all rhythms many times and get your ears tired. If you feel like you need a pause, feel free to take it. Your judgement is expected to be lucid. <br />
              Also, please, take the test in a quiet place, or use your headphones. Stay focused, it will not take much time. <br />
              The test is intended to last a maximum of 15 min. <br />
              <br /> 

              Thanks again for you collaboration. <br />
              <br />

              In the next page you are going to listen to some examples with varying levels of complexity.
  


    - type: generic
      id: training_1
      name: Training No.1
      content: >
               In the following pages there will be many rhythmic patterns of varying complexity. <br/>
               To let you have a preliminary idea of the complexity gradient present in the test, 
               here below some examples that you are going to listen again in the real test are reported. <br/>
               Among these examples there are very easy patterns from a rhythmic point of view, as well as really complex ones, and compromises. <br/><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_004/3 - Costante.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_003/14 - Random.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_004/13 - Random.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_001/2 - Costante.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_003/page_004/3 - Gerarchia.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_002/page_003/29 - Human.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_001/19 - Gerarchia.mp3' type='audio/mp3'></audio><br/>


    

      # PAGE 1 OF RATING
    - type: likert_multi_stimulus
      id: Rating_page_1
      name: Rate Rhythm Complexity (1st of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      mustRate: True
      mustPlayback: ended
      stimuli:
          Rhtyhm_2104R: configs/resources/audio/patterns/dataset_002/page_001/4 - Random.mp3
          Rhtyhm_2111H: configs/resources/audio/patterns/dataset_002/page_001/11 - Human.mp3
          Rhtyhm_2112H: configs/resources/audio/patterns/dataset_002/page_001/12 - Human.mp3
          Rhtyhm_2114G: configs/resources/audio/patterns/dataset_002/page_001/14 - Gerarchia.mp3
          Rhtyhm_2115G: configs/resources/audio/patterns/dataset_002/page_001/15 - Gerarchia.mp3
          Rhtyhm_2119C: configs/resources/audio/patterns/dataset_002/page_001/19 - Costante.mp3
          Rhtyhm_2123G: configs/resources/audio/patterns/dataset_002/page_001/23 - Gerarchia.mp3
          Rhtyhm_2125R: configs/resources/audio/patterns/dataset_002/page_001/25 - Random.mp3
          Rhtyhm_2128H: configs/resources/audio/patterns/dataset_002/page_001/28 - Human.mp3
          Rhtyhm_2128R: configs/resources/audio/patterns/dataset_002/page_001/28 - Random.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  

  
      # PAGE 2 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_2
      name: Rate Rhythm Complexity (2nd of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      mustRate: True
      mustPlayback: ended
      stimuli:
          Rhtyhm_2201R: configs/resources/audio/patterns/dataset_002/page_002/1 - Random.mp3
          Rhtyhm_2202R: configs/resources/audio/patterns/dataset_002/page_002/2 - Random.mp3
          Rhtyhm_2205R: configs/resources/audio/patterns/dataset_002/page_002/5 - Random.mp3
          Rhtyhm_2208C: configs/resources/audio/patterns/dataset_002/page_002/8 - Costante.mp3
          Rhtyhm_2216H: configs/resources/audio/patterns/dataset_002/page_002/16 - Human.mp3
          Rhtyhm_2220G: configs/resources/audio/patterns/dataset_002/page_002/20 - Gerarchia.mp3
          Rhtyhm_2220R: configs/resources/audio/patterns/dataset_002/page_002/20 - Random.mp3
          Rhtyhm_2222R: configs/resources/audio/patterns/dataset_002/page_002/22 - Random.mp3
          Rhtyhm_2223R: configs/resources/audio/patterns/dataset_002/page_002/23 - Random.mp3
          Rhtyhm_2225H: configs/resources/audio/patterns/dataset_002/page_002/25 - Human.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  



      # PAGE 3 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_3
      name: Rate Rhythm Complexity (3rd of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      mustRate: True
      mustPlayback: ended
      stimuli:
          Rhtyhm_2303R: configs/resources/audio/patterns/dataset_002/page_003/3 - Random.mp3
          Rhtyhm_2306H: configs/resources/audio/patterns/dataset_002/page_003/6 - Human.mp3
          Rhtyhm_2307C: configs/resources/audio/patterns/dataset_002/page_003/7 - Costante.mp3
          Rhtyhm_2309C: configs/resources/audio/patterns/dataset_002/page_003/9 - Costante.mp3
          Rhtyhm_2309H: configs/resources/audio/patterns/dataset_002/page_003/9 - Human.mp3
          Rhtyhm_2309R: configs/resources/audio/patterns/dataset_002/page_003/9 - Random.mp3
          Rhtyhm_2321H: configs/resources/audio/patterns/dataset_002/page_003/21 - Human.mp3
          Rhtyhm_2322G: configs/resources/audio/patterns/dataset_002/page_003/22 - Gerarchia.mp3
          Rhtyhm_2326H: configs/resources/audio/patterns/dataset_002/page_003/26 - Human.mp3
          Rhtyhm_2329H: configs/resources/audio/patterns/dataset_002/page_003/29 - Human.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
         

  
      # PAGE 4 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_4
      name: Rate Rhythm Complexity (4th of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      mustRate: True
      mustPlayback: ended
      stimuli:
          Rhythm_2401C: configs/resources/audio/patterns/dataset_002/page_004/1 - Costante.mp3
          Rhythm_2407G: configs/resources/audio/patterns/dataset_002/page_004/7 - Gerarchia.mp3
          Rhythm_2408H: configs/resources/audio/patterns/dataset_002/page_004/8 - Human.mp3
          Rhythm_2410G: configs/resources/audio/patterns/dataset_002/page_004/10 - Gerarchia.mp3
          Rhythm_2412C: configs/resources/audio/patterns/dataset_002/page_004/12 - Costante.mp3
          Rhythm_2418G: configs/resources/audio/patterns/dataset_002/page_004/18 - Gerarchia.mp3
          Rhythm_2418R: configs/resources/audio/patterns/dataset_002/page_004/18 - Random.mp3
          Rhythm_2419R: configs/resources/audio/patterns/dataset_002/page_004/19 - Random.mp3
          Rhythm_2422H: configs/resources/audio/patterns/dataset_002/page_004/22 - Human.mp3
          Rhythm_2424H: configs/resources/audio/patterns/dataset_002/page_004/24 - Human.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
         

    - type: finish
      name: Thank you
      content: Thank you for attending! <br/> <br/>
      popupContent: Your results were sent. Goodbye and have a nice day   
      showResults: true
      writeResults: true
      questionnaire:
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
          - type: number 
            label: Years of formal music training
            name: years_training
            min: 0
            max: 100
            default: 5
          - type: text
            label: Country
            name: country
          - type: long_text
            label: Feedback
            name: feedback
            optional: true
